iCREATE TABLE Marvin;

CREATE TABLE messages (
  mid INT NOT NULL AUTO_INCREMENT,
  uid INT NOT NULL,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  uid_from INT NOT NULL,
  PRIMARY KEY (mid,uid, uid_from),
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (uid_from) REFERENCES users(uid) ON DELETE CASCADE
);


CREATE TABLE users (
  uid INT NOT NULL AUTO_INCREMENT,
  name CHAR(20),
  token VARCHAR(500) NOT NULL UNIQUE,
    PRIMARY KEY (uid)
  );
